# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'carGUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fileButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileButton.setGeometry(QtCore.QRect(480, 50, 75, 23))
        self.fileButton.setObjectName("fileButton")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(40, -10, 691, 561))
        self.tableView.setObjectName("tableView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 40, 131, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.fileLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileLineEdit.setGeometry(QtCore.QRect(200, 50, 271, 20))
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 80, 90, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(480, 80, 75, 23))
        self.SearchButton.setObjectName("SearchButton")
        self.carLicenseLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.carLicenseLineEdit.setGeometry(QtCore.QRect(200, 80, 271, 20))
        self.carLicenseLineEdit.setObjectName("carLicenseLineEdit")
        self.resultShowText = QtWidgets.QTextBrowser(self.centralwidget)
        self.resultShowText.setGeometry(QtCore.QRect(120, 106, 551, 101))
        self.resultShowText.setObjectName("resultShowText")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 0, 231, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 50, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 220, 551, 301))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.mapshow = QtWidgets.QWidget(self.centralwidget)
        self.mapshow.setGeometry(QtCore.QRect(119, 229, 541, 291))
        self.mapshow.setObjectName("mapshow")
        self.gridLayoutWidget = QtWidgets.QWidget(self.mapshow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 551, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.carPic = QtWidgets.QPushButton(self.centralwidget)
        self.carPic.setGeometry(QtCore.QRect(490, 209, 75, 20))
        self.carPic.setObjectName("carPic")
        self.mapShow = QtWidgets.QPushButton(self.centralwidget)
        self.mapShow.setGeometry(QtCore.QRect(570, 208, 75, 23))
        self.mapShow.setObjectName("mapShow")
        self.tableView.raise_()
        self.fileButton.raise_()
        self.label.raise_()
        self.fileLineEdit.raise_()
        self.label_2.raise_()
        self.SearchButton.raise_()
        self.carLicenseLineEdit.raise_()
        self.resultShowText.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.label_4.raise_()
        self.mapshow.raise_()
        self.carPic.raise_()
        self.mapShow.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.fileButton.clicked.connect(self.fileLineEdit.show)
        self.SearchButton.clicked.connect(self.carLicenseLineEdit.show)
        self.carLicenseLineEdit.editingFinished.connect(self.carLicenseLineEdit.show)
        self.fileLineEdit.editingFinished.connect(self.fileLineEdit.show)
        self.pushButton.clicked.connect(self.fileLineEdit.show)
        self.mapShow.clicked.connect(self.mapshow.show)
        self.carPic.clicked.connect(self.mapshow.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fileButton.setText(_translate("MainWindow", "选择文件"))
        self.label.setText(_translate("MainWindow", "视频路径："))
        self.label_2.setText(_translate("MainWindow", "查询车牌："))
        self.SearchButton.setText(_translate("MainWindow", "查询"))
        self.resultShowText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "车牌信息查询"))
        self.pushButton.setText(_translate("MainWindow", "视频处理"))
        self.carPic.setText(_translate("MainWindow", "图片显示"))
        self.mapShow.setText(_translate("MainWindow", "地图显示"))

